#!/bin/sh

echo "Running Gitleaks on files in . ..."
gitleaks dir -v --config gitleaks.toml

GITLEAKS_RESULT=$?

if [ $GITLEAKS_RESULT -ne 0 ]; then
    echo "❌ Gitleaks found issues. Commit aborted."
    exit 1
fi

echo "✅ Gitleaks passed."

echo "Running Tflint on .tf files in ./infrastructure ..."
tflint --chdir=infrastructure/

TFLINT_RESULT=$?

if [ $TFLINT_RESULT -ne 0 ]; then
    echo "❌ Tflint found issues. Commit aborted."
    exit 1
fi

echo "✅ Tflint passed."

echo "Running Checkov on .tf files in ./infrastructure ..."
checkov --framework terraform -d infrastructure

CHECKOV_RESULT=$?

if [ $CHECKOV_RESULT -ne 0 ]; then
    echo "❌ Checkov found issues. Commit aborted."
    exit 1
fi

echo "✅ Checkov passed."

echo "Formatting Terraform configuration ..."
terraform fmt -recursive infrastructure/
echo "✅ Formatting completed."

echo "Running Terraform init to update .terraform.lock.hcl file ..."
terraform init -upgrade
echo "✅ Terraform init completed."

echo "Staging changed files ..."
git add .
echo "✅ Staging completed."

echo "✅ Proceeding with commit."

exit 0
