trigger:
- main

variables:
  terraformVersion: '1.11.4'
  azureSubscription: 'SPN-accesaplayground'

stages:
- stage: Plan
  jobs:
  - job: Plan
    displayName: "Validate and Plan"
    pool:
      vmImage: ubuntu-22.04
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Terraform init..."
          terraform init
          echo "Terraform validate..."
          terraform validate
          echo "Terraform plan..."
          terraform plan -out=tfplan -input=false
        addSpnToEnvironment: true
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'

    - task: PublishPipelineArtifact@1
      displayName: "Publish tfplan"
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/infrastructure/tfplan'
        artifactName: 'tfplan'
        publishLocation: 'pipeline'

- stage: Apply
  displayName: "Apply"
  dependsOn: Plan
  condition: succeeded()
  jobs:
    - deployment: Apply
      displayName: "Apply"
      pool:
        vmImage: ubuntu-22.04
      environment: 'management-cluster-prod'  
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none

              - checkout: self
              
              - task: DownloadPipelineArtifact@2
                displayName: "Download tfplan to infra dir"
                inputs:
                  buildType: 'current'
                  artifactName: 'tfplan'
                  targetPath: '$(System.DefaultWorkingDirectory)/infrastructure'
              
              - task: AzureCLI@2
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    echo "Terraform init..."
                    terraform init
                    echo "Terraform apply started..."
                    terraform apply tfplan
                  addSpnToEnvironment: true
                  workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
